[workspace]
resolver = "2"
members = [
    "chap-1",
    "chap-2",
    "chap-3",
    "chap-4",
    "chap-5-1",
    "chap-5-2",
    "chap-6",
    "chap-7-1",
    "chap-7-2",
    "chap-8-1",
    "chap-8-2",
    "chap-9-1",
    "chap-9-2",
    "chap-10-1",
    "chap-10-2",
]


